"""initial_schema

Revision ID: 3de76149c0b1
Revises: 
Create Date: 2026-09-05 16:53:01.592312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3de76149c0b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_companies_slug')
    )
    op.create_index('ix_companies_slug', 'companies', ['slug'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('careers_pages',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('published_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_version_id'], ['career_page_versions.id'], name='fk_careers_pages_published_version', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_careers_pages_company_id')
    )
    op.create_index('ix_careers_pages_company_id', 'careers_pages', ['company_id'], unique=False)
    op.create_table('company_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'EDITOR', name='member_role'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_company_members_user_company')
    )
    op.create_index('ix_company_members_company_id', 'company_members', ['company_id'], unique=False)
    op.create_index('ix_company_members_user_id', 'company_members', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', name='job_type'), nullable=False),
    sa.Column('experience_level', sa.Enum('ENTRY', 'MID', 'SENIOR', 'LEAD', name='experience_level'), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', name='job_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_company_department', 'jobs', ['company_id', 'department'], unique=False)
    op.create_index('ix_jobs_company_job_type', 'jobs', ['company_id', 'job_type'], unique=False)
    op.create_index('ix_jobs_company_location', 'jobs', ['company_id', 'location'], unique=False)
    op.create_index('ix_jobs_company_status', 'jobs', ['company_id', 'status'], unique=False)
    op.create_table('career_page_versions',
    sa.Column('career_page_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='version_status'), nullable=False),
    sa.Column('sections_config', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('theme_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_page_id'], ['careers_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_page_id', 'version_number', name='uq_career_page_versions_page_version')
    )
    op.create_index('ix_career_page_versions_career_page_id', 'career_page_versions', ['career_page_id'], unique=False)
    op.create_index('ix_career_page_versions_page_published', 'career_page_versions', ['career_page_id', 'status'], unique=False)
    op.create_index('ix_career_page_versions_status', 'career_page_versions', ['status'], unique=False)
    # NOTE: The circular FK (careers_pages.published_version_id -> career_page_versions.id)
    # is intentionally NOT created here. It is added in the next migration:
    #   4852d64316e9_add_circular_fk.py
    # This separation is required because career_page_versions did not exist when
    # careers_pages was first created in this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_career_page_versions_status', table_name='career_page_versions')
    op.drop_index('ix_career_page_versions_page_published', table_name='career_page_versions')
    op.drop_index('ix_career_page_versions_career_page_id', table_name='career_page_versions')
    op.drop_table('career_page_versions')
    op.drop_index('ix_jobs_company_status', table_name='jobs')
    op.drop_index('ix_jobs_company_location', table_name='jobs')
    op.drop_index('ix_jobs_company_job_type', table_name='jobs')
    op.drop_index('ix_jobs_company_department', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_company_members_user_id', table_name='company_members')
    op.drop_index('ix_company_members_company_id', table_name='company_members')
    op.drop_table('company_members')
    op.drop_index('ix_careers_pages_company_id', table_name='careers_pages')
    # NOTE: fk_careers_pages_published_version is dropped by 4852d64316e9_add_circular_fk.py downgrade.
    op.drop_table('careers_pages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_companies_slug', table_name='companies')
    op.drop_table('companies')
    # Drop PostgreSQL enum types (autogenerate omits these)
    op.execute('DROP TYPE IF EXISTS version_status')
    op.execute('DROP TYPE IF EXISTS member_role')
    op.execute('DROP TYPE IF EXISTS job_type')
    op.execute('DROP TYPE IF EXISTS experience_level')
    op.execute('DROP TYPE IF EXISTS job_status')
    # ### end Alembic commands ###

